name: Secretlint
on:
    - push
    - pull_request

permissions:
    contents: read

jobs:
    secretlint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v5.0.0
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Lint with Secretlint
              run: npx secretlint "**/*"
